### ISSUE TITLE
Workaround for ID verification

### ISSUE THREAD

**Issue by utsavsingh899** [vijaiaeroastro/irccloud#4]
The Heroku app asks for ID verification which has to be done by an international credit card. Since students don't have that a workaround would be highly appreciated.

**Comment by vijaiaeroastro** [comment]
I am aware of this issue. This is necessary not an issue in the code. Heroku basically wants people to add a credit card if you want to use an addon. That's all. I will have to revert back to older version of the script which didn't need a scheduler. I will close the issue now.
