### ISSUE TITLE
Assumes current directory

### ISSUE THREAD

**Issue by glitchphan** [vijaiaeroastro/irccloud#5]
If you run the python script from outside of its directory, like from a cron job, it gets a FileNotFoundError for user_agents.json. The script should check what directory itself is in and check there for other files.

Also if you run the script more than once, as suggested from a crontab entry, then just more and more instances will accumulate. It should check to see if it's already running, or you should suggest that the crontab entry does the check (pgrep?).

Thanks for taking the time to make this and release it.

**Comment by vijaiaeroastro** [comment]
I really didn't test the crontab option. It was suggested by someone else. I always used heroku. If you would like to fix this, kindly place a pull request :smiley:

**Comment by EliteOfGods** [comment]
@glitchphan could you try my [master](https://github.com/EliteOfGods/irccloud) branch to confirm if it works for you too (if you still use IRCCloud)?

Regarding:
> Also if you run the script more than once, as suggested from a crontab entry, then just more and more instances will accumulate. It should check to see if it's already running, or you should suggest that the crontab entry does the check (pgrep?).

When the cronjob script was created, the `irccloud.py` could be used both in Heroku as in your own machine.

It was then modified to the use with Heroku and stopped working as expected in personal machine with a crontab entry.

My fixes should now make it usable with Heroku and personal servers.


Cheers
