### ISSUE TITLE
We can use github actions now

### ISSUE THREAD

**Issue by petronny** [vijaiaeroastro/irccloud#6]
1. Add this workflow file
https://github.com/petronny/irccloud/commit/1f1d1f403f11d186d3d0c3431cf73ac5ccb10b03
1. Drop this commit aa5078684f12ead538871d3864b153f41595ad0e
timeloop is not needed anymore
1. Set the enviroments in Settings -> Secerts

**Comment by vijaiaeroastro** [comment]
Hey @petronny, this seems quite cool. I will try to test it today and merge it. Can you place a pull request?

**Comment by petronny** [comment]
Well I can't use pull request to drop a commit...

**Comment by vijaiaeroastro** [comment]
Alright. I will make the modifications myself after testing.
